name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 8 * * 0-6

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'

      #          npm run test
      - name: Build
        run: |
          npm ci
          npm run build

      #          npm run release
      - name: Release
        id: release
        run: |
          VERSION=$(npm run get-version)
          echo "$VERSION"
          echo "::set-output name=PROJECT_VERSION::$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Display version
        run: echo ${{ steps.release.outputs.PROJECT_VERSION }}

#deroffal/github-stats:latest,
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: deroffal/github-stats:${{ steps.release.outputs.PROJECT_VERSION }}
